---
apiVersion: codemowers.cloud/v1beta1
kind: OIDCMiddlewareClient
metadata:
  name: whoami
spec:
  uri: 'https://whoami.ee-west-1.codemowers.io/'
  headerMapping:
    user: Remote-Username
    email: Remote-Email
    groups: Remote-Groups
    name: Remote-Name
