{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "passmower.fullname" . }}
  labels:
    {{- merge (include "passmower.chartLabels" . | fromYaml) (deepCopy .Values.podMonitor.labels) (deepCopy .Values.commonLabels) | toYaml | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "passmower.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.podMonitor.interval }}
{{- end }}
